name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
